// Generado por scripts/empaquetar-migraciones.ts — no editar a mano.
// Se regenera con `npm run db:generate`.

export type Migracion = {
  /** El nombre que le puso drizzle-kit. Es lo que se guarda como aplicado. */
  tag: string;
  sentencias: string[];
};

export const MIGRACIONES_SQLITE: Migracion[] = [
  {
    "tag": "0000_organic_rawhide_kid",
    "sentencias": [
      "CREATE TABLE `exercises` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text,\n\t`nombre` text NOT NULL,\n\t`musculo_principal` text NOT NULL,\n\t`musculos_secundarios` text DEFAULT '[]' NOT NULL,\n\t`equipamiento` text NOT NULL,\n\t`unilateral` integer DEFAULT false NOT NULL,\n\t`visibilidad` text DEFAULT 'privado' NOT NULL,\n\t`version` integer DEFAULT 1 NOT NULL,\n\t`creado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\t`actualizado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE INDEX `exercises_musculo_principal_idx` ON `exercises` (`musculo_principal`);",
      "CREATE TABLE `flame_log` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`semana_inicio` text NOT NULL,\n\t`sesiones_planeadas` integer DEFAULT 0 NOT NULL,\n\t`sesiones_cumplidas` integer DEFAULT 0 NOT NULL,\n\t`descansos_planeados` integer DEFAULT 0 NOT NULL,\n\t`nivel` integer DEFAULT 0 NOT NULL,\n\t`nivel_piso` integer DEFAULT 0 NOT NULL,\n\t`creado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\t`actualizado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE UNIQUE INDEX `flame_log_user_semana_uq` ON `flame_log` (`user_id`,`semana_inicio`);",
      "CREATE TABLE `food_log` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`food_id` text NOT NULL,\n\t`comida` text NOT NULL,\n\t`cantidad_gramos` real NOT NULL,\n\t`registrado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\t`creado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\t`actualizado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`food_id`) REFERENCES `foods`(`id`) ON UPDATE no action ON DELETE restrict\n);",
      "CREATE INDEX `food_log_user_registrado_idx` ON `food_log` (`user_id`,`registrado_en`);",
      "CREATE INDEX `food_log_food_idx` ON `food_log` (`food_id`);",
      "CREATE TABLE `foods` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text,\n\t`nombre` text NOT NULL,\n\t`marca` text,\n\t`codigo_barras` text,\n\t`porcion_gramos` real DEFAULT 100 NOT NULL,\n\t`kcal` real NOT NULL,\n\t`proteina_g` real DEFAULT 0 NOT NULL,\n\t`carbohidratos_g` real DEFAULT 0 NOT NULL,\n\t`grasa_g` real DEFAULT 0 NOT NULL,\n\t`fuente` text DEFAULT 'manual' NOT NULL,\n\t`fuente_id` text,\n\t`creado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\t`actualizado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE INDEX `foods_codigo_barras_idx` ON `foods` (`codigo_barras`);",
      "CREATE TABLE `friendships` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`solicitante_id` text NOT NULL,\n\t`destinatario_id` text NOT NULL,\n\t`estado` text DEFAULT 'pendiente' NOT NULL,\n\t`compartir_descanso` integer DEFAULT true NOT NULL,\n\t`compartir_disponibilidad` integer DEFAULT true NOT NULL,\n\t`creado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\t`actualizado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\tFOREIGN KEY (`solicitante_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`destinatario_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE UNIQUE INDEX `friendships_par_uq` ON `friendships` (`solicitante_id`,`destinatario_id`);",
      "CREATE INDEX `friendships_destinatario_idx` ON `friendships` (`destinatario_id`);",
      "CREATE TABLE `gym_machines` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`gym_id` text NOT NULL,\n\t`exercise_id` text,\n\t`nombre` text NOT NULL,\n\t`marca` text,\n\t`equipamiento` text NOT NULL,\n\t`placa_a_kg` text,\n\t`peso_minimo_kg` real,\n\t`incremento_kg` real,\n\t`cantidad` integer DEFAULT 1 NOT NULL,\n\t`creado_por` text,\n\t`creado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\t`actualizado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\tFOREIGN KEY (`gym_id`) REFERENCES `gyms`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`exercise_id`) REFERENCES `exercises`(`id`) ON UPDATE no action ON DELETE set null,\n\tFOREIGN KEY (`creado_por`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE set null\n);",
      "CREATE INDEX `gym_machines_gym_idx` ON `gym_machines` (`gym_id`);",
      "CREATE TABLE `gyms` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`creado_por` text,\n\t`nombre` text NOT NULL,\n\t`direccion` text,\n\t`ciudad` text,\n\t`latitud` real,\n\t`longitud` real,\n\t`verificado` integer DEFAULT false NOT NULL,\n\t`visibilidad` text DEFAULT 'publico' NOT NULL,\n\t`creado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\t`actualizado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\tFOREIGN KEY (`creado_por`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE set null\n);",
      "CREATE INDEX `gyms_ciudad_idx` ON `gyms` (`ciudad`);",
      "CREATE TABLE `measurements` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`medido_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\t`peso_kg` real,\n\t`altura_cm` real,\n\t`pecho_cm` real,\n\t`cintura_cm` real,\n\t`cadera_cm` real,\n\t`brazo_cm` real,\n\t`muslo_cm` real,\n\t`pantorrilla_cm` real,\n\t`grasa_pct` real,\n\t`grasa_origen` text,\n\t`grasa_margen_pct` real,\n\t`visibilidad` text DEFAULT 'privado' NOT NULL,\n\t`creado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\t`actualizado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE INDEX `measurements_user_medido_idx` ON `measurements` (`user_id`,`medido_en`);",
      "CREATE TABLE `photos` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`tipo` text NOT NULL,\n\t`angulo` text,\n\t`session_id` text,\n\t`measurement_id` text,\n\t`ruta_local` text,\n\t`clave_remota` text,\n\t`tomada_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\t`visibilidad` text DEFAULT 'privado' NOT NULL,\n\t`creado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\t`actualizado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE set null,\n\tFOREIGN KEY (`measurement_id`) REFERENCES `measurements`(`id`) ON UPDATE no action ON DELETE set null\n);",
      "CREATE INDEX `photos_user_tomada_idx` ON `photos` (`user_id`,`tomada_en`);",
      "CREATE TABLE `routine_exercises` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`routine_id` text NOT NULL,\n\t`exercise_id` text NOT NULL,\n\t`orden` integer NOT NULL,\n\t`series_objetivo` integer,\n\t`repeticiones_objetivo` integer,\n\t`descanso_segundos` integer,\n\t`creado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\t`actualizado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\tFOREIGN KEY (`routine_id`) REFERENCES `routines`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`exercise_id`) REFERENCES `exercises`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE INDEX `routine_exercises_routine_idx` ON `routine_exercises` (`routine_id`,`orden`);",
      "CREATE TABLE `routines` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`nombre` text NOT NULL,\n\t`notas` text,\n\t`copiada_de` text,\n\t`visibilidad` text DEFAULT 'privado' NOT NULL,\n\t`creado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\t`actualizado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE INDEX `routines_user_idx` ON `routines` (`user_id`);",
      "CREATE TABLE `sessions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`time_block_id` text,\n\t`routine_id` text,\n\t`gym_id` text,\n\t`inicio` integer NOT NULL,\n\t`fin` integer,\n\t`notas` text,\n\t`visibilidad` text DEFAULT 'privado' NOT NULL,\n\t`creado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\t`actualizado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`time_block_id`) REFERENCES `time_blocks`(`id`) ON UPDATE no action ON DELETE set null,\n\tFOREIGN KEY (`routine_id`) REFERENCES `routines`(`id`) ON UPDATE no action ON DELETE set null,\n\tFOREIGN KEY (`gym_id`) REFERENCES `gyms`(`id`) ON UPDATE no action ON DELETE set null\n);",
      "CREATE INDEX `sessions_user_inicio_idx` ON `sessions` (`user_id`,`inicio`);",
      "CREATE INDEX `sessions_time_block_idx` ON `sessions` (`time_block_id`);",
      "CREATE INDEX `sessions_routine_idx` ON `sessions` (`routine_id`);",
      "CREATE TABLE `sets` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`session_id` text NOT NULL,\n\t`exercise_id` text NOT NULL,\n\t`gym_machine_id` text,\n\t`orden` integer NOT NULL,\n\t`repeticiones` integer NOT NULL,\n\t`peso_kg` real,\n\t`placa` integer,\n\t`esfuerzo` integer,\n\t`lado` text DEFAULT 'ambos' NOT NULL,\n\t`calentamiento` integer DEFAULT false NOT NULL,\n\t`completada_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\t`creado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\t`actualizado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`exercise_id`) REFERENCES `exercises`(`id`) ON UPDATE no action ON DELETE restrict,\n\tFOREIGN KEY (`gym_machine_id`) REFERENCES `gym_machines`(`id`) ON UPDATE no action ON DELETE set null\n);",
      "CREATE INDEX `sets_session_orden_idx` ON `sets` (`session_id`,`orden`);",
      "CREATE INDEX `sets_user_exercise_idx` ON `sets` (`user_id`,`exercise_id`,`completada_en`);",
      "CREATE INDEX `sets_exercise_idx` ON `sets` (`exercise_id`);",
      "CREATE INDEX `sets_gym_machine_idx` ON `sets` (`gym_machine_id`);",
      "CREATE TABLE `time_blocks` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`tipo` text NOT NULL,\n\t`titulo` text,\n\t`inicio` integer NOT NULL,\n\t`fin` integer NOT NULL,\n\t`repeticion` text DEFAULT 'ninguna' NOT NULL,\n\t`repeticion_hasta` integer,\n\t`gym_id` text,\n\t`visibilidad` text DEFAULT 'privado' NOT NULL,\n\t`creado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\t`actualizado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`gym_id`) REFERENCES `gyms`(`id`) ON UPDATE no action ON DELETE set null\n);",
      "CREATE INDEX `time_blocks_user_inicio_idx` ON `time_blocks` (`user_id`,`inicio`);",
      "CREATE TABLE `users` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`email` text NOT NULL,\n\t`nombre` text NOT NULL,\n\t`creado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\t`actualizado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL\n);",
      "CREATE UNIQUE INDEX `users_email_unique` ON `users` (`email`);"
    ]
  },
  {
    "tag": "0001_cute_lizard",
    "sentencias": [
      "CREATE TABLE `injuries` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`zona` text NOT NULL,\n\t`lado` text DEFAULT 'ambos' NOT NULL,\n\t`descripcion` text,\n\t`desde` text,\n\t`activa` integer DEFAULT true NOT NULL,\n\t`visibilidad` text DEFAULT 'privado' NOT NULL,\n\t`creado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\t`actualizado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE INDEX `injuries_user_activa_idx` ON `injuries` (`user_id`,`activa`);",
      "CREATE TABLE `profiles` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`objetivos` text DEFAULT '[]' NOT NULL,\n\t`compromiso` text,\n\t`sexo` text,\n\t`edad_declarada` integer,\n\t`edad_declarada_en` text,\n\t`gym_principal_id` text,\n\t`comidas_por_dia` integer,\n\t`desayuna` integer,\n\t`ayuno_intermitente` integer,\n\t`quien_cocina` text,\n\t`cardio_tipo` text,\n\t`cardio_minutos` integer,\n\t`cardio_intensidad` text,\n\t`suplementos` text DEFAULT '[]' NOT NULL,\n\t`horas_sueno_min` integer,\n\t`horas_sueno_max` integer,\n\t`hora_de_acostarse` text,\n\t`reloj` text DEFAULT 'ninguno' NOT NULL,\n\t`reloj_modelo` text,\n\t`duerme_con_reloj` integer,\n\t`exigencia` text,\n\t`onboarding_paso` integer DEFAULT 0 NOT NULL,\n\t`onboarding_completado_en` integer,\n\t`creado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\t`actualizado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`gym_principal_id`) REFERENCES `gyms`(`id`) ON UPDATE no action ON DELETE set null\n);",
      "CREATE UNIQUE INDEX `profiles_user_id_unique` ON `profiles` (`user_id`);",
      "CREATE TABLE `user_foods` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`food_id` text NOT NULL,\n\t`habitual` integer DEFAULT true NOT NULL,\n\t`creado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\t`actualizado_en` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`food_id`) REFERENCES `foods`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE UNIQUE INDEX `user_foods_par_uq` ON `user_foods` (`user_id`,`food_id`);",
      "CREATE INDEX `user_foods_food_idx` ON `user_foods` (`food_id`);"
    ]
  }
];
